#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    binary=str(bin(n))
    number=binary[2:]
    
    count=0
    result=0
    for i in number:
        if i=='1':
            count+=1
        else:
            if count>result:
                result=count
            count=0
    if count>result:
                result=count
    print(result)
